name: MasterDeployPortfolio
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest #Select the operating system
    strategy:
      matrix:
        node-version: [10.x] #Define node version to be used
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1 
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages 
      run: npm install
    - name: Deploy to GH Pages #Set credentials to allow server to clone repo then build and deploy
      run: |
        git config --global user.email ${{ secrets.EMAIL_PORTFOLIO }}
        git config --global user.name ${{ secrets.USERNAME_PORTFOLIO }}
        git remote set-url origin https://${{ secrets.PERSONAL_ACCESS_TOKEN_PORTFOLIO }}@github.com/${{ secrets.USERNAME_PORTFOLIO }}/react-portfolio.git
        npm run deploy